services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  broker1:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
  
  server:
    build: ./DockerCompose/server
    ports:
      - "50052:50052"  # Porta 50051 del container esposta sulla 8081 dell'host

    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=yfinance_db
      - DATABASE_PORT=3306
    depends_on:
      - db
    restart: always
  
  data_collector:
    build: ./DockerCompose/DataCollector
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=yfinance_db
      - KAFKA_BROKER=broker1:29092
    depends_on:
      - db
      - broker1
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"         # Password per l'utente root
      MYSQL_DATABASE: "yfinance_db"      # Nome del database creato automaticamente       
    ports:
      - "3308:3306"  # Mappa la porta 3306 del container alla porta 3308 dell'host

    volumes:
      - ./db-data:/var/lib/mysql  # Volume per salvare i dati del database
  
  telegram_bot:
    build: ./DockerCompose/Get_chat_id
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=yfinance_db
      - BOT_TOKEN=7587852566:AAH0pXlB_VHM-UW1BZwhed5A9WzQnvLd5y8

    depends_on:
      - db
    restart: always


  alert_system:
    build: ./DockerCompose/AlertSystem
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=yfinance_db
      - KAFKA_BROKER=broker1:29092
    depends_on:
      - db
      - broker1
    restart: always

  alert_notifier_system:
    build: ./DockerCompose/AlertNotifierSystem
    environment:
      - KAFKA_BROKER=broker1:29092
    depends_on:
      - broker1
    restart: always
      
volumes:
  db-data:  # Definizione del volume per il database
